### PR TITLE
Issue 315 of front end Fixed

### PR DESCRIPTION
**Pull request by Gauravseta**
Alter script commenting below

### CODE REVIEW

**Comment by Gauravseta** [comment]
CREATE TABLE IF NOT EXISTS `institution_locale` (
`id` bigint(20) NOT NULL AUTO_INCREMENT,
  `institution_name` varchar(256) NOT NULL,
  `description` varchar(1024) NOT NULL,
  `locale_id` bigint(20) NOT NULL,
  `institution_id` bigint(20) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `UK_institution_locale_lc1` (`locale_id`, `institution_id`),
      INDEX `il_lo_fk_idx` (`locale_id`),
      INDEX `il_io_fk_idx1` (`institution_id`),
      CONSTRAINT `ill_lo_fk`
      FOREIGN KEY (`locale_id`)
      REFERENCES `locale` (`id`)
      ON DELETE CASCADE
      ON UPDATE NO ACTION,
      CONSTRAINT `il_io_fk`
      FOREIGN KEY (`institution_id`)
      REFERENCES `institution` (`id`)
      ON DELETE CASCADE
      ON UPDATE NO ACTION
) ENGINE=InnoDB;

**Comment by Gauravseta** [comment]
insert into institution_locale values (1,'Pupilo','PUPILO es una innovadora iniciativa sin ánimo de lucro que',2,1);
insert into institution_locale values (2,'Lideres del Mañana','Líderes del Mañana busca potencializar la formación y desarroll',2,2);
insert into institution_locale values (3,'Incubación de Empresas CIETT','El objetivo principal del área de Incubadora de Empresas',2,3);
insert into institution_locale values (4,'Pupilo','PUPILO is an innovative no profit initiative that continuously grows thanks to the volunteering of business and professionals that are commited with society',1,1);
insert into institution_locale values (5,'Lideres del Mañana','Líderes del Mañana looks to potentializing the formation and development of young talented Mexicans, that due to their econocmic and social condition require a full scholarship to study at the Tec',1,2);
insert into institution_locale values (6,'Incubación de Empresas CIETT','The main objective of the Business Incubator area is to create and develop micro and small businesses so they are profitable and innovative.  This is done through counseling, training, profesional consulting in any of the business areas as well as follow through to facilitate access to financial sources',1,3);

**Comment by huangqun** [comment]
@Gauravseta it's not working and it took over 15 mins just to run the tests:
image

PLEASE, make sure it works for you first before you submit a PR.

**Comment by Gauravseta** [comment]
But these issues are not mine.not due to my code changes

**Comment by Gauravseta** [comment]
I will check again and raise a perfect PR though it is perfect.

**Comment by huangqun** [comment]
@Gauravseta it is, because before I merged your code, all unit tests passed. After I merged your code, 4 of the tests failed.

**Pull request closed without merging**
