### PR TITLE
issue_331 of front End fixed.

### PR DESCRIPTION
**Pull request by Gauravseta**
Use this in reference to issue_331 of front end repo

### CODE REVIEW

**Comment by huangqun** [comment]
Which exact task from our list does this fix cover? I still don't see the reason why we have to update the backend service for this. `ionic serve` seems to work properly as long as the config files and build process are correct. Please clarify why this code change to the backend is necessary.

**Comment by huangqun** [comment]
Code is not documented at all, so even if the code change necessary, this cannot be accepted as is.

**Comment by Gauravseta** [comment]
Shall I update in readme.MD why this file is required?
Or I have to mention in websecurityconfig.java?

**Comment by huangqun** [comment]
No, you can just clarify here why the file is necessary. Because `ionic serve` works for me already without this file.

**Comment by Gauravseta** [comment]
I have already added why file is required.
I guess it is front end PR I wrote that's why u may have missed it.I will copy again

**Comment by huangqun** [comment]
@Gauravseta my point is, it already works properly, so why we need that java file?

It didn't work for Ward but I think that was a configuration issue.

**Pull request closed without merging**
