### PR TITLE
issue_315 of front end Repo Fixed.

### PR DESCRIPTION
**Pull request by Gauravseta**
Mentee profile localization issue solved.

Note: No front end repo changes are required for issue_315 hence raising only backend repo.

### CODE REVIEW

**Comment by huangqun** [comment]
@Gauravseta there are many issues with this fix:
1. a lot of coding and documentation issues like the other ones
2. I don't think this solution is appropriate, if I understand correctly you are creating the new table to localize the description field of the instituation_program table, but if you check the instituation_program table carefully, you can see that the english version and Spanish version of the Pupilo program are created as separate rows in this same table, both name and description are already localized, so why do we need an extra table to complicate things?

Let me know if I missed anything, for now I have to reject this one. You can have 12 more hours to come up with a better solution.

**Comment by Gauravseta** [comment]
@huangqun ward had said that create institution_locale table and I feel that is correct way to do that because even country skill locale tables are created.
On front end repo ward commented.

**Comment by huangqun** [comment]
Both country and skill tables won't have entries with different locales in the same table. For example: country table only has english country names.

But instituation_program is different, it has both English and Spanish programs that are actually the same but only with different locale, for example: Pupilo-English and Pupilo-Español.

If you are going to add the instituation_program_locale table, then the instituation_program table should NOT have mixed records but only English programs, and then the instituation_program_locale table would have ones with different locales.

Even so, it's still not quite correct, since all records in country table will have a corresponding localized record in the country_locale table, but some programs may only have an English version, or only Spanish version.

That's why I don't feel this is the correct way to do it.

**Comment by Gauravseta** [comment]
I have added institution locale not institution program locale table

**Comment by huangqun** [comment]
I know, but that table is actually for institution programs instead of institutions, so the table name  and some columns names were not appropriate either.

**Comment by Gauravseta** [comment]
So finally I don't have to add any table rite? 
Fetch it from instition program table,but then data for few institution missing, shall I add Spanish version in institution program.

**Comment by huangqun** [comment]
No, I'm not suggesting how you should do it, what I'm saying is what you did was not right. You need to come up with a better solution for this. 

IMO an acceptable solution is to add a locale_id column to the instituation_program table, but let's wait for @ward-appirio to comment on this.

**Comment by Gauravseta** [comment]
I hope no one else comes now to still this issue as it is done just simple modification might be needed if required.

**Pull request closed without merging**
