### PR TITLE
Issue 317 of front end fixed

### PR DESCRIPTION
**Pull request by Gauravseta**
Front End PR for Issue_317 is raised.
Note: Please use this PR in conjuction with front end PR of issue_317.
Necessary documentation like alter scripts will be commented below.

### CODE REVIEW

**Comment by Gauravseta** [comment]
ddl.sql has been modified, locale_id column is added in mentee and mentor table.
Alter table script for changes made is : 
/** For Mentor table **/
ALTER TABLE mentor 
ADD COLUMN `locale_id` BIGINT NOT NULL
ADD CONSTRAINT `m_li_fk`
    FOREIGN KEY (`locale_id`)
    REFERENCES `locale` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION

/** ends**/

/** for Mentee table**/
ALTER TABLE mentee 
ADD COLUMN `locale_id` BIGINT NOT NULL
CONSTRAINT `me_li_fk`
    FOREIGN KEY (`locale_id`)
    REFERENCES `locale` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION
/** ends **/

**Comment by huangqun** [comment]
@Gauravseta I took a quick look at the code (without testing) and I still see several places with code indention issues, to give you an example:
http://take.ms/yPWNf
http://take.ms/uvKKL

This is not supposed to be so hard, if you use any modern IDE it should take care of code indention automatically. Please fix all of them (**not just the two examples above**) and update your PR.

**Comment by huangqun** [comment]
Also make sure all unit tests still pass by running `mvn clean test`

**Comment by Gauravseta** [comment]
Yes I am using modern ide , I made sure everything is OK, I guess I need a tool now which will draw a vertical line by that only I will verify now.

**Comment by Gauravseta** [comment]
new Pr has been raised

**Pull request closed without merging**
