### PR TITLE
Fix 318

### PR DESCRIPTION
**Pull request by arifnyet**
updated the calculation, fixed the naming documentation and indent

### CODE REVIEW

**Comment by arifnyet** [comment]
@huangqun new pr

**Comment by huangqun** [comment]
@arifnyet there are still several issues with code documentation, check this:

fix 318 by arifnyet pull request 84 topcoderinc hpe-lp-mentorme-services 2017-05-23 10-58-31


Please note the param section must match the param names in the method signature exactly. And you need to have doc for the method as well as return value.

**Comment by arifnyet** [comment]
@huangqun updated

**Comment by huangqun** [comment]
@arifnyet this is making the unit tests failing, we need them fixed or we have to reject this fix:
http://take.ms/h8mqi

**Comment by Gauravseta** [comment]
@huangqun  my code working proper, I told a;ready something is failing.

**Comment by arifnyet** [comment]
@huangqun @Gauravseta fixing...

**Pull request merged**
