### PR TITLE
Issue 298

### PR DESCRIPTION
**Pull request by coderReview**
Fix for issue in https://github.com/topcoderinc/HPE-LP-MentorMe/issues/298.

### CODE REVIEW

**Comment by huangqun** [comment]
@coderReview please give me access to your fork so I can merge this and test it locally before accepting the PR.

Thanks!

**Comment by coderReview** [comment]
@huangqun done

**Comment by huangqun** [comment]
@coderReview I'm getting unit test failures after these code changes. Could you check into this?

**Comment by huangqun** [comment]
@coderReview here's what I see:
image
I'm sure it's related to your fix because before I apply the fix the tests all work. Please address as soon as you can.

**Comment by coderReview** [comment]
I am fixing this. The goal object should be removed from the Json. However,
you won't be able to update a goal through MenteeMentorGoal controller. If
you need to update a Goal, the GoalController should be used. This is to
avoid issues with hibernate, because both MenteeMentorGoal and
GoalController can point to the same Document object.

2017-05-22 7:01 GMT-03:00 huangqun <notifications@github.com>:

**Comment by huangqun** [comment]
ok, let me know when this is fixed @coderReview 

Thanks!

**Comment by huangqun** [comment]
@coderReview any updates on this please?

**Comment by coderReview** [comment]
I am still looking at this. I am testing to make sure I didn't break any
functionality. But the main issue is that we have objects in
MenteeMentorGoal that are also defined in MenteeMentorGoal.Goal. Maybe we
could remove the ones defined in MenteeMentorGoal and use the ones defines
in MenteeMentorGoal.Goal.

2017-05-24 1:59 GMT-03:00 huangqun <notifications@github.com>:

**Comment by huangqun** [comment]
@coderReview so now are you just trying to fix the unit test or perhaps the original fix had some bugs too? If the latter, I will have to revert this first.

**Comment by coderReview** [comment]
@huangqun in the application the fix seems to be working. But in the tests
it has more testcases. I am fixing the tests but I am also changing the
main code. When I started working in this issue, I could not update the
MenteeMentorGoal because of an Hibernate error. I had to fix the error
along with the issue fix (close mentee/mentor program when all goals are
completed). Fixing this error is more complicated than the issue fix
itself.

2017-05-24 23:58 GMT-03:00 huangqun <notifications@github.com>:

**Comment by huangqun** [comment]
@coderReview ok, I need to revert this PR then, please submit a new one once this is fixed. I'll also reopen that issue.

**Comment by huangqun** [comment]
@coderReview any positive progress on this one?

**Comment by coderReview** [comment]
Yes. All tests are working. I've committed to my repository. You can take a
look. Still need to validate with the real application.

2017-05-26 12:02 GMT-03:00 huangqun <notifications@github.com>:

**Comment by huangqun** [comment]
@coderReview it's been too long, I will have to let someone else give it a try based on the rules.

**Pull request merged**
